/*
 * Copyright 2013-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.eulerframework.security.authentication.apple;

import org.eulerframework.security.authentication.device.DeviceAttestRegistration;
import org.springframework.security.core.AuthenticationException;

/**
 * Service interface for validating Apple App Attest attestation and assertion objects.
 * <p>
 * Implementations are responsible for CBOR decoding, certificate chain verification,
 * nonce validation (attestation), and signature verification (assertion) according to
 * Apple's App Attest documentation.
 * <p>
 * Both methods return {@link DeviceAttestRegistration} containing the validated cryptographic
 * data. Callers are responsible for constructing {@link AppleAppAttestUser} or performing
 * user lookup/creation as needed.
 *
 * @see <a href="https://developer.apple.com/documentation/devicecheck/validating-apps-that-connect-to-your-server">
 *     Validating Apps That Connect to Your Server</a>
 */
public interface AppleAppAttestValidationService {

    /**
     * Validate an App Attest attestation object (initial device registration), persist
     * the registration, and return the validated registration data.
     *
     * @param keyId       the key identifier generated by {@code DCAppAttestService}
     * @param attestation the Base64-encoded attestation object
     * @param challenge   the challenge used when generating the attestation
     * @return the validated and persisted registration
     * @throws AuthenticationException if validation fails
     */
    DeviceAttestRegistration validateAttestation(String keyId, String attestation, String challenge) throws AuthenticationException;

    /**
     * Validate an App Attest assertion object (re-authentication with a registered device)
     * and return the registration data.
     *
     * @param keyId     the key identifier of the previously registered device
     * @param assertion the Base64-encoded assertion object
     * @param challenge the challenge used when generating the assertion
     * @return the registration associated with the validated assertion
     * @throws AuthenticationException if validation fails
     */
    DeviceAttestRegistration validateAssertion(String keyId, String assertion, String challenge) throws AuthenticationException;
}
