/*
 * Copyright 2013-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.eulerframework.security.authentication.otp;

import org.springframework.util.Assert;

import java.time.Duration;

/**
 * Input of an {@link OneTimePasswordService#generate(GenerateOneTimePasswordRequest)} call:
 * everything the ticket service needs to mint and persist a ticket, without
 * any knowledge of policy resolution or delivery.
 * <p>
 * Mirrors the shape of Spring Security's {@code GenerateOneTimeTokenRequest}
 * (a request object in, the persisted token out) adapted to the two-value
 * ticket + code model.
 *
 * @param channel    logical delivery channel name (e.g. {@code sms}, {@code email})
 * @param recipient  channel-addressable delivery target (phone number, email, ...)
 * @param purpose    optional, opaque business label; not interpreted by the framework
 * @param otpLength  length of the OTP value to generate (e.g. {@code 6})
 * @param expiresIn  how long the ticket remains valid
 * @param fixedOtp   when non-empty, used verbatim as the OTP value instead of
 *                   generating one (test-account short-circuit); {@code null}
 *                   in the normal path
 */
public record GenerateOneTimePasswordRequest(
        String channel,
        String recipient,
        String purpose,
        int otpLength,
        Duration expiresIn,
        String fixedOtp) {

    public GenerateOneTimePasswordRequest {
        Assert.hasText(channel, "channel must not be empty");
        Assert.hasText(recipient, "recipient must not be empty");
        Assert.isTrue(otpLength > 0, "otpLength must be positive");
        Assert.notNull(expiresIn, "expiresIn must not be null");
    }

    /**
     * Convenience constructor for the normal path where the OTP value is
     * generated by the ticket service.
     */
    public GenerateOneTimePasswordRequest(String channel, String recipient, String purpose,
                                          int otpLength, Duration expiresIn) {
        this(channel, recipient, purpose, otpLength, expiresIn, null);
    }
}
