/*
 * Copyright 2013-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.eulerframework.security.authentication.otp;

import org.springframework.util.Assert;

import java.time.Instant;

/**
 * Server-side state of a single OTP issuance.
 * <p>
 * An {@code OtpTicket} is generated by
 * {@link OtpTicketIssueAuthenticationProvider} and persisted by an
 * {@link OtpTicketService}. It is later consumed by
 * {@link OtpTicketService#consume(String, String, String, String)} when the
 * holder of the {@code code_verifier} (PKCE) presents the OTP value back to
 * the server.
 * <p>
 * The {@code otp} value (the actual one-time password sent to the user) and
 * the {@code codeChallenge}/{@code codeChallengeMethod} (PKCE binding to the
 * issuing client) are kept here so that the consume step can verify both
 * possession of the OTP and possession of the original PKCE secret.
 *
 * @param ticketId            opaque, URL-safe identifier of this ticket
 *                            (e.g. {@code ot_xxxxxxxx})
 * @param channel             logical channel name used to deliver the OTP
 *                            (e.g. {@code sms}, {@code email})
 * @param recipient           the {@code OtpChannel}-addressable target of the
 *                            OTP (phone number, email, push token, ...)
 * @param purpose             optional, opaque business label that
 *                            {@link OtpChannel} implementations may use to
 *                            select templates or wording. The framework does
 *                            not interpret this value
 * @param otp                 the one-time password value as plain text
 * @param codeChallenge       PKCE code challenge bound to this ticket
 *                            (RFC 7636); may be {@code null} when PKCE is
 *                            disabled (see
 *                            {@code euler.security.otp.pkce.enabled})
 * @param codeChallengeMethod PKCE code challenge method, currently always
 *                            {@code S256} when present; may be {@code null}
 *                            when {@code codeChallenge} is {@code null}
 * @param expiresAt           when this ticket becomes invalid
 * @param failureCount        number of failed consume attempts so far
 * @param consumed            whether this ticket has already been successfully
 *                            consumed
 */
public record OtpTicket(
        String ticketId,
        String channel,
        String recipient,
        String purpose,
        String otp,
        String codeChallenge,
        String codeChallengeMethod,
        Instant expiresAt,
        int failureCount,
        boolean consumed) {

    public OtpTicket {
        Assert.hasText(ticketId, "ticketId must not be empty");
        Assert.hasText(channel, "channel must not be empty");
        Assert.hasText(recipient, "recipient must not be empty");
        Assert.hasText(otp, "otp must not be empty");
        Assert.notNull(expiresAt, "expiresAt must not be null");
        Assert.isTrue(failureCount >= 0, "failureCount must not be negative");
    }

    /**
     * Returns a copy of this ticket with {@code failureCount} incremented by one.
     */
    public OtpTicket withFailureIncremented() {
        return new OtpTicket(this.ticketId, this.channel, this.recipient, this.purpose,
                this.otp, this.codeChallenge, this.codeChallengeMethod,
                this.expiresAt, this.failureCount + 1, this.consumed);
    }

    /**
     * Returns a copy of this ticket marked as consumed.
     */
    public OtpTicket markConsumed() {
        return new OtpTicket(this.ticketId, this.channel, this.recipient, this.purpose,
                this.otp, this.codeChallenge, this.codeChallengeMethod,
                this.expiresAt, this.failureCount, true);
    }
}
