CREATE TABLE SYS_USER
    (
        ID VARCHAR(36) NOT NULL,
        USERNAME VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255) NULL,
        MOBILE VARCHAR(255) NULL,
        PASSWORD VARCHAR(255) NOT NULL,
        ACCOUNT_NON_EXPIRED bit NOT NULL,
        ACCOUNT_NON_LOCKED bit NOT NULL,
        CREDENTIALS_NON_EXPIRED bit NOT NULL,
        ENABLED bit NOT NULL,
        ROOT bit NULL,
        PRIMARY KEY (ID),
        CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
        CONSTRAINT UK_SYS_USER_EMAIL UNIQUE (EMAIL),
        CONSTRAINT UK_SYS_USER_MOBILE UNIQUE (MOBILE)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
CREATE TABLE SYS_GROUP
    (
        ID VARCHAR(36)  NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NULL,
        PRIMARY KEY (ID),
        CONSTRAINT UK_SYS_GROUP UNIQUE (NAME)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
CREATE TABLE SYS_AUTHORITY
    (
        AUTHORITY VARCHAR(255) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NULL,
        PRIMARY KEY (AUTHORITY),
        CONSTRAINT UK_SYS_AUTHORITY UNIQUE (NAME)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SYS_USER_GROUP
    (
        USER_ID  VARCHAR(36) NOT NULL,
        GROUP_ID VARCHAR(36) NOT NULL,
        PRIMARY KEY (USER_ID, GROUP_ID),
        CONSTRAINT FK_SYS_USER_GROUP_UID FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID),
        CONSTRAINT FK_SYS_USER_GROUP_GID FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
CREATE TABLE SYS_GROUP_AUTHORITY
    (
        GROUP_ID  VARCHAR(36)  NOT NULL,
        AUTHORITY VARCHAR(255) NOT NULL,
        PRIMARY KEY (GROUP_ID, AUTHORITY),
        CONSTRAINT FK_SYS_GROUP_AUTHORITY_GID FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID),
        CONSTRAINT FK_SYS_GROUP_AUTHORITY_AID FOREIGN KEY (AUTHORITY) REFERENCES SYS_AUTHORITY (AUTHORITY)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SYS_USER (ID, USERNAME, EMAIL, MOBILE, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, ROOT) 
VALUES ('00000000-0000-0000-0000-000000000000', 'root', null, null, 'NaN', true, true, true, true, true);
INSERT INTO SYS_USER (ID, USERNAME, EMAIL, MOBILE, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, ROOT) 
VALUES (uuid(), 'admin', null, null, 'NaN', true, true, true, true, null);
INSERT INTO SYS_GROUP (ID, DESCRIPTION, NAME) VALUES ('00000000-0000-0000-0000-000000000000', '管理员', '管理员');
INSERT INTO SYS_AUTHORITY (AUTHORITY, DESCRIPTION, NAME) VALUES ('ADMIN', '管理员', '管理员');
INSERT INTO SYS_USER_GROUP (USER_ID, GROUP_ID) VALUES (
(SELECT ID FROM SYS_USER WHERE USERNAME = 'admin'), '00000000-0000-0000-0000-000000000000');
INSERT INTO SYS_GROUP_AUTHORITY (GROUP_ID, AUTHORITY) VALUES ('00000000-0000-0000-0000-000000000000', 'ADMIN');
