CREATE TABLE
    SYS_USER
    (
        ID VARCHAR(36) NOT NULL,
        USERNAME VARCHAR(255) NOT NULL,
        PASSWORD VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255),
        MOBILE VARCHAR(255),
        FULL_NAME VARCHAR(255),
        ACCOUNT_NON_EXPIRED bit NOT NULL,
        ACCOUNT_NON_LOCKED bit NOT NULL,
        CREDENTIALS_NON_EXPIRED bit NOT NULL,
        ENABLED bit NOT NULL,
        ROOT bit,
        RESET_TOKEN VARCHAR(255),
        RESET_TOKEN_EXPIRE_TIME DATETIME,
        PRIMARY KEY (ID),
        CONSTRAINT UK_7vkgonfffndxkyvn4dynxgj79 UNIQUE (USERNAME),
        CONSTRAINT UK_f259lj3q4eic86d2lm8blpyuf UNIQUE (EMAIL),
        CONSTRAINT UK_dghx7fv54kny2dtcblmtdjfij UNIQUE (MOBILE),
        CONSTRAINT UK_72yrria5jh774xaapc2d4ibvm UNIQUE (RESET_TOKEN)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_GROUP
    (
        ID VARCHAR(36) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255),
        PRIMARY KEY (ID),
        CONSTRAINT UK_o40mn7kacjbeqya5dyam08et9 UNIQUE (NAME)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_AUTHORITY
    (
        ID VARCHAR(36) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        AUTHORITY VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255),
        PRIMARY KEY (ID),
        CONSTRAINT UK_bhklc2v6lju3mxttpx3s84aj4 UNIQUE (AUTHORITY),
        CONSTRAINT UK_96njp3i4upbwyqaeitmmf0ocm UNIQUE (NAME)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_GROUP_AUTHORITY
    (
        GROUP_ID VARCHAR(36) NOT NULL,
        AUTHORITY_ID VARCHAR(36) NOT NULL,
        PRIMARY KEY (GROUP_ID, AUTHORITY_ID),
        CONSTRAINT FK11760kgj2a22ec60tsw7vn186 FOREIGN KEY (AUTHORITY_ID) REFERENCES SYS_AUTHORITY
        (ID) ,
        CONSTRAINT FKr6yekpud0xs5jtj7d0562x90t FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID),
        INDEX FK11760kgj2a22ec60tsw7vn186 (AUTHORITY_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_USER_GROUP
    (
        USER_ID VARCHAR(36) NOT NULL,
        GROUP_ID VARCHAR(36) NOT NULL,
        PRIMARY KEY (USER_ID, GROUP_ID),
        CONSTRAINT FK1vv9renj19k3jwp1l6rsggjvs FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID) ,
        CONSTRAINT FKa0xvlp1wkjucldvy1y2lomyhn FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID),
        INDEX FKa0xvlp1wkjucldvy1y2lomyhn (GROUP_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


insert into SYS_USER
(ID,USERNAME,PASSWORD,FULL_NAME,ACCOUNT_NON_EXPIRED,ACCOUNT_NON_LOCKED,CREDENTIALS_NON_EXPIRED,ENABLED,ROOT)
values 
(uuid(), 'root', 'NaN', 'root', true, true, true, true, true),
(uuid(), 'admin', 'NaN', 'Administrator', true, true, true, true, false);