CREATE TABLE
    SYS_USER
    (
        ID VARCHAR(36) NOT NULL,
        USERNAME VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255),
        MOBILE VARCHAR(255),
        PASSWORD VARCHAR(255) NOT NULL,
        ACCOUNT_NON_EXPIRED bit NOT NULL,
        ACCOUNT_NON_LOCKED bit NOT NULL,
        CREDENTIALS_NON_EXPIRED bit NOT NULL,
        ENABLED bit NOT NULL,
        ROOT bit,
        PRIMARY KEY (ID),
        CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
        CONSTRAINT UK_SYS_USER_EMAIL UNIQUE (EMAIL),
        CONSTRAINT UK_SYS_USER_MOBILE UNIQUE (MOBILE)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SYS_USER (ID, USERNAME, EMAIL, MOBILE, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, ROOT) VALUES ('00000000-0000-0000-0000-000000000000', 'root', null, null, 'NaN', true, true, true, true, true);
INSERT INTO SYS_USER (ID, USERNAME, EMAIL, MOBILE, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, ROOT) VALUES (uuid(), 'admin', null, null, 'NaN', true, true, true, true, null);



CREATE TABLE
    SYS_USER
    (
        ID VARCHAR(36) NOT NULL,
        USERNAME VARCHAR(255) NOT NULL,
        PASSWORD VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255),
        MOBILE VARCHAR(255),
        FULL_NAME VARCHAR(255),
        ACCOUNT_NON_EXPIRED bit NOT NULL,
        ACCOUNT_NON_LOCKED bit NOT NULL,
        CREDENTIALS_NON_EXPIRED bit NOT NULL,
        ENABLED bit NOT NULL,
        ROOT bit,
        SIGN_UP_TIME DATETIME NOT NULL,
        CONSTRAINT PK_SYS_USER PRIMARY KEY (ID),
        CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
        CONSTRAINT UK_SYS_USER_EMAIL UNIQUE (EMAIL),
        CONSTRAINT UK_SYS_USER_MOBILE UNIQUE (MOBILE)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_GROUP
    (
        ID VARCHAR(36) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255),
        CONSTRAINT PK_SYS_GROUP PRIMARY KEY (ID),
        CONSTRAINT UK_SYS_GROUP_NAME UNIQUE (NAME)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_AUTHORITY
    (
        AUTHORITY VARCHAR(255) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255),
        CONSTRAINT PK_SYS_AUTHORITY PRIMARY KEY (AUTHORITY),
        CONSTRAINT UK_SYS_AUTHORITY_NAME UNIQUE (NAME)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_GROUP_AUTHORITY
    (
        GROUP_ID VARCHAR(36) NOT NULL,
        AUTHORITY VARCHAR(36) NOT NULL,
        CONSTRAINT PK_SYS_GROUP_AUTHORITY PRIMARY KEY (GROUP_ID, AUTHORITY),
        CONSTRAINT FK_SYS_GROUP_AUTHORITY_AUTHORITY FOREIGN KEY (AUTHORITY) REFERENCES SYS_AUTHORITY (AUTHORITY) ,
        CONSTRAINT FK_SYS_GROUP_AUTHORITY_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID),
        INDEX FK_SYS_GROUP_AUTHORITY_AUTHORITY (AUTHORITY)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE
    SYS_USER_GROUP
    (
        USER_ID VARCHAR(36) NOT NULL,
        GROUP_ID VARCHAR(36) NOT NULL,
        CONSTRAINT PK_SYS_USER_GROUP PRIMARY KEY (USER_ID, GROUP_ID),
        CONSTRAINT FK_SYS_USER_GROUP_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID) ,
        CONSTRAINT FK_SYS_USER_GROUP_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID),
        INDEX FK_SYS_USER_GROUP_GROUP (GROUP_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


insert into SYS_USER
(ID,USERNAME,PASSWORD,FULL_NAME,ACCOUNT_NON_EXPIRED,ACCOUNT_NON_LOCKED,CREDENTIALS_NON_EXPIRED,ENABLED,ROOT,SIGN_UP_TIME)
values 
(uuid(), 'root', 'NaN', 'root', true, true, true, true, true, now()),
(uuid(), 'admin', 'NaN', 'Administrator', true, true, true, true, false, now());